### PR TITLE
solution & project directories refactor; extracted "logic" parts into own botLogic sub project

### PR DESCRIPTION
**Pull request by 0x1911**
Good morning,

i promise i am done now with major refactoring of the project.

I have redone the pushes 3afa8bc0dd5c98212c1b4284ba13d30f51810a57 and 1b13d0937f1897b5dbf35f946d8521bbc3058e89 so merging shouldnt be a problem. :)

Sorry if you have to refactor uncommited files on your end. I can assist if you want though.

kind regards

### CODE REVIEW

**Comment by 0x1911** [comment]
I hope you feel encouraged on more logic features in the future.

And dont be offended by the clean up.. Its still not very clean, but should be a lot easier to extend now.

If you have any further questions or notes, just let me know.

**Comment by 0x1911** [comment]
For the changed logo + added icon please check the image below.

unbenannt

**Comment by Sen66** [comment]
What font are you using at the logo?

**Comment by 0x1911** [comment]
I have no idea.
Was created by a buddy of mine.

**Comment by Sen66** [comment]
I dont want to have a font that Im not allowed to use. Thats why I ask.

**Comment by Sen66** [comment]
Is the XP/hour stuff working for you?

**Comment by 0x1911** [comment]
The font is from http://www.dafont.com/de/pocket-monk.font
As we dont use it commercially it should be fine to use.

However if you are running down that road -> Using a trademarked product name as project name isn't that good of an idea either. ;)

xp/h pok/h might have a bug in it. It was a long night.
I'll look into it shortly.

**Comment by Sen66** [comment]
I just fixed xp/h, poke/h and made the bot a bit faster. Ill push it into master later this evening

**Comment by 0x1911** [comment]
Oh excellent! :)
Just started looking into it myself.

Will my changes here get pulled into your repo?
So i can start a fresh fork afterwards to avoid further branching conflicts.

**Comment by Sen66** [comment]
Yeah I'll pullthem in my repo soon.

**Pull request closed without merging**
