### PR TITLE
Location reference

### PR DESCRIPTION
**Pull request by sh4t**
Updated to include bhelper.Main in output.

### CODE REVIEW

**Comment by 0x1911** [comment]
Sorry about the extra work i have cause you good sir.

**Comment by sh4t** [comment]
It's okay, I just cloned a fresh copy and tested with the PR; works fine.  I really want to get to the point where configuration is "per location" because ultimately, I use tons of locations and they are all around my actual Physical area or parts of the city at night etc and would like to be able to discern them easily, configure what to keep and evolve, etc.  This is just a step in that direction.

**Comment by Sen66** [comment]
In the GUI I actually want to have a dropdown to select the most common spots like Sydney, Central park where everybody is and also an opttion to use your own location.

**Comment by 0x1911** [comment]
@Sen66: You might have to pull #29 before merging this one. :)

**Pull request merged**
