### PR TITLE
Remove duplicate and a typo

### PR DESCRIPTION
**Pull request by spot88**

### CODE REVIEW

**Comment by Sen66** [comment]
What is the duplicate and what is the typo? lol

**Comment by spot88** [comment]
PokemonId.NidoranFemale, and you are having // that should not be there.

**Comment by Sen66** [comment]
The "//" is there because the last character of the array would be a "," then.
And where else is PokemonId.NidoranFemale? Do you mean in the other function? These 2 functions dont affect each other so it is no duplicate?

**Comment by spot88** [comment]
PokemonId.NidoranFemale, is on line 344 and 363.

PokemonId.Eevee//, is on line 504 the "//" should not be there because then it would comment out the "," and it will not take into account the Ignore on Dratini? - Or have i misunderstood

**Comment by Sen66** [comment]
Okay I see the duplicate, thanks for that. But the other thing is not a typo.
`            PokemonId[] doNotTransfer = new[] //these will not be transferred even when below the CP threshold
            { // DO NOT EMPTY THIS ARRAY
                //PokemonId.Pidgey,
                //PokemonId.Slowpoke,
                //PokemonId.Drowzee,
                //PokemonId.Gastly,
                //PokemonId.Goldeen,
                //PokemonId.Staryu,
                PokemonId.Magikarp,
                PokemonId.Eevee//,
                //PokemonId.Dratini
            };`
The last item in an array should have no comma. Comma => we have another item in this array after this one. But after Eevee is no other item because Dratini is commented.

**Comment by spot88** [comment]
Aha, okay I understand now. Might be better to do it like this then: 
//PokemonId.Staryu,
//PokemonId.Dratini,
   PokemonId.Magikarp,
   PokemonId.Eevee             
            };`

No more confusion for a not so much experienced programmer :)

**Comment by Sen66** [comment]
When you "correct" your Pull request Ill merge it :)

**Comment by spot88** [comment]
There.

**Pull request merged**
